export const BaseDeDados = [
  {
    id: 1,
    nome: "Vestido Bordô",
    categoria: "Corpo Inteiro",
    imagem: "src/assets/imagens/vestidovinho.png",
    descricao: "Leve e confortável",
    tamanhos: ["P", "M", "G"],
    tecido: "Linho",
  },
  {
    id: 2,
    nome: "Macacão Elegante",
    categoria: "Corpo Inteiro",
    imagem: "src/assets/imagens/macacaoelegante.png",
    descricao: "Perfeito para dias frios",
    tamanhos: ["P", "M", "G", "GG"],
    tecido: "Algodão",
  },
  {
    id: 3,
    nome: "Calça Jeans Wide Leg",
    categoria: "Calças",
    imagem: "src/assets/imagens/wideleg.png",
    descricao: "Para quem tem estilo",
    tamanhos: ["P", "M", "G"],
    tecido: "Jeans",
  },
  {
    id: 4,
    nome: "Blusa Feminina Linho",
    categoria: "Blusas",
    imagem: "src/assets/imagens/blusasd.png",
    descricao: "Leve como o verão",
    tamanhos: ["PP", "P", "M", "G"],
    tecido: "Linho",
  },
  {
    id: 5,
    nome: "Camisa Masculina",
    categoria: "Blusas",
    imagem: "src/assets/imagens/blusasmasc.png",
    descricao: "Elegante e estilosa",
    tamanhos: ["P", "M", "G", "GG"],
    tecido: "Linho",
  },
  {
    id: 6,
    nome: "Body",
    categoria: "Corpo Inteiro",
    imagem: "src/assets/imagens/bodys.png",
    descricao: "Magnitude em uma só peça",
    tamanhos: ["P", "M", "G"],
    tecido: "Algodão",
  },
  {
    id: 7,
    nome: "Boné Masculino",
    categoria: "Acessórios",
    imagem: "src/assets/imagens/bones.png",
    descricao: "Elegante e descontraído",
    tamanhos: ["Único"],
    tecido: "Linho",
  },
  {
    id: 8,
    nome: "Pulseiras de Prata",
    categoria: "Acessórios",
    imagem: "src/assets/imagens/pulseiras.png",
    descricao: "Peça que realça seu brilho",
    tamanhos: ["Único"],
    tecido: "Prata 925",
  },
  {
    id: 9,
    nome: "Bandana Premium",
    categoria: "Acessórios",
    imagem: "src/assets/imagens/bandana.png",
    descricao: "100% Linho",
    tamanhos: ["Único"],
    tecido: "Linho",
  },
  {
    id: 10,
    nome: "Manta",
    categoria: "Acessórios",
    imagem: "src/assets/imagens/manta.png",
    descricao: "100% Algodão",
    tamanhos: ["Único"],
    tecido: "Algodão",
  },
  {
    id: 11,
    nome: "Calça Jeans Flare",
    categoria: "Calças",
    imagem: "src/assets/imagens/calcaflare.jpeg",
    descricao: "A cara do inverno",
    tamanhos: ["PP", "P", "M", "G", "GG"],
    tecido: "Jeans",
  },
  {
    id: 12,
    nome: "Jaqueta Jeans",
    categoria: "Blusas",
    imagem: "src/assets/imagens/jaquetajeans.jpeg",
    descricao: "Bonito e elegânte",
    tamanhos: ["P", "M", "G", "GG"],
    tecido: "Jeans",
  },
  {
    id: 13,
    nome: "Vestido Seda Slip",
    categoria: "Corpo Inteiro",
    imagem: "src/assets/imagens/vestidoseda.jpeg",
    descricao: "Leveza que exalta",
    tamanhos: ["PP", "P", "M", "G"],
    tecido: "Seda",
  },
  {
    id: 14,
    nome: "Blusa Seda Feminina",
    categoria: "Blusas",
    imagem: "src/assets/imagens/blusadeseda.jpeg",
    descricao: "Fresca para um dia de calor",
    tamanhos: ["P", "M", "G"],
    tecido: "Seda",
  },
];
