export const BaseDeDados = [
  {
    id: 1,
    nome: "vestido",
    categoria: "feminino",
    imagem: "src/assets/imagens/vestido.jpeg",
    descricao: "a",
  },
  {
    id: 2,
    nome: "macacão",
    categoria: "unisex",
    imagem: "src/assets/imagens/macacão.jpeg",
    descricao: "a",
  },
  {
    id: 3,
    nome: "calça",
    categoria: "unisex",
    imagem: "src/assets/imagens/calça.jpeg",
    descricao: "a",
  },
  {
    id: 4,
    nome: "blusa",
    categoria: "feminino",
    imagem: "src/assets/imagens/blusa.jpeg",
    descricao: "a",
  },
  {
    id: 5,
    nome: "camisa",
    categoria: "masculino",
    imagem: "src/assets/imagens/camisa.jpeg",
    descricao: "a",
  },
  {
    id: 6,
    nome: "body",
    categoria: "unisex",
    imagem: "src/assets/imagens/body.jpeg",
    descricao: "a",
  },
  {
    id: 7,
    nome: "boné",
    categoria: "masculino",
    imagem: "src/assets/imagens/boné.jpeg",
    descricao: "a",
  },
  {
    id: 8,
    nome: "faixa de cabelo",
    categoria: "feminino",
    imagem: "src/assets/imagens/faixa.jpeg",
    descricao: "a",
  },
  {
    id: 9,
    nome: "sapatinho de tricô",
    categoria: "unisex",
    imagem: "src/assets/imagens/sapatinho.jpeg",
    descricao: "a",
  },
  {
    id: 10,
    nome: "manta",
    categoria: "unisex",
    imagem: "src/assets/imagens/manta.jpeg",
    descricao: "a",
  },
];
